# netlify.toml
[build]
  publish   = "dist"
  functions = "netlify/functions"

[build.environment]
  VITE_GIT_COMMIT = "$COMMIT_REF"
  VITE_GIT_BRANCH = "$BRANCH"
  VITE_DEPLOY_URL = "$DEPLOY_URL"
  VITE_DEPLOY_PRIME_URL = "$DEPLOY_PRIME_URL"
  VITE_CONTEXT = "$CONTEXT"
  VITE_APP_VERSION = "1.0.0"

[dev]
  command    = "npm run dev"   # ← ご自身の Vite 起動コマンド
  targetPort = 5173            # ← Vite が listen するポート
  port       = 8888            # ← Netlify Dev がブラウザに見せるポート
  framework  = "#custom"       # ★ ここを変更！
  autoLaunch = true
    edgeFunctionsPort = 0

# 以下はそのまま ─────────────
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma        = "no-cache"
    Expires       = "0"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options      = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy        = "strict-origin-when-cross-origin"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200


  VITE_APP_VERSION = "1.0.0"