# netlify.toml (2025‑04‑21)
[build]
  publish   = "dist"
  functions = "netlify/functions"

[dev]
  command    = "npm run dev"
  framework  = "vite"
  targetPort = 5173
  port       = 8888
  autoLaunch = true

# キャッシュ制御ヘッダー
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
